todo_project/todo_list/urls.py
from django.urls import path

from django.views.generic import TemplateView

from . import views

#name space - to put this name in navbar like todo_list:list_of_todo - the name of the view
app_name = 'todo_list'

urlpatterns = [
    #template view
    #path("", TemplateView.as_view(template_name="todo_list/index.html"), name = 'index'),


    # path("", views.index_view, name="index"),

    #class based view
    path("", views.ToDoListView.as_view(), name = 'list_of_todo'),
    path("categories", views.CategoriesView.as_view(), name = 'categories'),
    path("done/", views.ToDoListDoneView.as_view(), name = 'done'),
    path("<int:pk>/", views.ToDoDetailView.as_view(), name="detail"),
    path("create/", views.TodoItemCreateView.as_view(), name="create"),
    path("<int:pk>/update/", views.TodoItemUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", views.TodoItemDeleteView.as_view(), name="delete"),
]

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import TemplateView

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"),name = 'index'),
    path('todo/', include('todo_list.urls')),
    
]

todo_project/todo_list/models.py
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ["id"]
        verbose_name = "Categorie"

    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class ToDoItem(models.Model):
    class Meta:
        ordering = ["id"]
        verbose_name = "ToDo Item"

    title = models.CharField(max_length=50,unique=True)
    done = models.BooleanField(default=False)
    description = models.TextField(blank=True, null=False)
    category_id = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True
    )
    archived = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todo_project/todo_list/forms.py
from django import forms
from .models import ToDoItem
from django.utils.translation import gettext_lazy as _


class TodoItemCreateForm(forms.ModelForm):
    class Meta:
        model = ToDoItem
        fields = ("title", "description")  # Ensure these match the model fields

        labels = {
            "title": _("Title of the todo"),
            "description": "Description of the todo",
        }

        help_texts = {
            "title": _("Enter a unique name of the task."),
            "description": _("Enter a short description of the task."),
        }

        error_messages = {
            "description": {
                "max_length": _("This description is too long."),
            },
            "title": {
                "max_length": _("Thisname is too long."),
            },
        }

        widgets = {
            "description": forms.Textarea(attrs={"cols": 80, "rows": 20}),
        }

class TodoItemUpdateForm(forms.ModelForm):
    class Meta(TodoItemCreateForm.Meta):
        fields = ("title",'done', "description") 

todo_project/todo_list/views.py
from django.shortcuts import render

from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseRedirect,
)
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView

from .models import ToDoItem
from .models import Category
from .forms import TodoItemCreateForm
from .forms import TodoItemUpdateForm


def index_view(request: HttpRequest) -> HttpResponse:
    todo_items = ToDoItem.objects.order_by("-id").all()[:3]
    return render(
        request,
        template_name="todo_list/index.html",
        context={"todo_items": todo_items},
    )


class ToDoListView(ListView):
    # template_name = "todo_list/index.html"
    #queryset = ToDoItem.objects.all()
    queryset = ToDoItem.objects.filter(archived = False)
    # we can avoid using context_object_name if change in templates todo_list
    # to object_list
    context_object_name = "todo_list"

    # def get_context_data(self, **kwargs):
    # print(ToDoItem._meta.app_label)
    # print(ToDoItem._meta.model_name)
    # return super().get_context_data(**kwargs)

    def get_context_data(self, **kwargs):
        # Get context from parent class
        context = super().get_context_data(**kwargs)

        # Add categories to the context
        context["categories"] = Category.objects.all()

        return context


class CategoriesView(ListView):
    template_name = "todo_list/categories_list.html"
    queryset = Category.objects.all()
    context_object_name = "categories"


class ToDoListDoneView(ListView):
    # template_name = "todo_list/done_list.html"
    queryset = ToDoItem.objects.filter(done=True).all()
    context_object_name = "todo_list"


class ToDoDetailView(DetailView):
    model = ToDoItem


class TodoItemCreateView(CreateView):
    model = ToDoItem
    form_class = TodoItemCreateForm
    success_url = reverse_lazy("todo_list:list_of_todo")


class TodoItemUpdateView(UpdateView):
    model = ToDoItem
    form_class = TodoItemUpdateForm
    template_name_suffix='_update_form'
    success_url = reverse_lazy("todo_list:list_of_todo")

class TodoItemDeleteView(DeleteView):
    model = ToDoItem
  
    template_name_suffix='_delete_form'
    success_url = reverse_lazy("todo_list:list_of_todo")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)
    

todo_project/templates/base.html
<!DOCTYPE html>
<html lang="es">
  {% load static tailwind_tags %}

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}Base Title{% endblock title %}</title>

    {% tailwind_css %}
  </head>

  <body>
    {% include "components/navbar.html" %}

    {% block body %}
      Base Body!
      <h3>It is the {% now "jS of F" %}</h3>
    {% endblock body %}

    {% include "components/footer.html" %}
  </body>
</html>

todo_project/templates/components/footer.html
<footer>&copy;Django ToDo App</footer>

todo_project/templates/components/navbar.html
<nav class="navbar">
    <ul class="nav-list">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="{% url 'todo_list:list_of_todo' %}">List of Todos</a></li>
        <li><a href="{% url 'todo_list:done' %}">List of todos:done</a></li>
        <li><a href="{% url 'todo_list:categories' %}">Categories</a></li>
        <li><a href="{% url 'todo_list:create' %}">Create todo</a></li>
        
    </ul>
</nav>

<nav class="bg-gray-800 p-4">
    <ul class="flex space-x-6">
        <li><a href="{% url 'index' %}" class="text-white hover:text-gray-300">Home</a></li>
        <li><a href="#" class="text-white hover:text-gray-300">About</a></li>
        <li><a href="{% url 'todo_list:list_of_todo' %}" class="text-white hover:text-gray-300">List of Todos</a></li>
        <li><a href="{% url 'todo_list:done' %}" class="text-white hover:text-gray-300">List of Todos: Done</a></li>
        <li><a href="{% url 'todo_list:categories' %}" class="text-white hover:text-gray-300">Categories</a></li>
        <li><a href="{% url 'todo_list:create' %}" class="text-white hover:text-gray-300">Create Todo</a></li>
    </ul>
</nav>

todo_project/templates/index.html
{% extends "base.html" %}

todo_project/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

todo_project/todo_list/templates/todo_list/base.html
{% extends 'base.html' %}

{% block footer %}
	ToDo list
{% endblock %}

todo_project/todo_list/templates/todo_list/categories_list.html
{% extends 'todo_list/base.html' %}

{% block title %}
  Categories List
{% endblock %}

{% block body %}
<h3>Categories:</h3>
<ul>
    {% for category in categories %}
        <li>{{ category.name }}</li>
    {% endfor %}
</ul>
{% endblock %}
    

todo_project/todo_list/templates/todo_list/components/todo_items_list.html
<!-- This is a comment <ul>

    {% for item in object_list %}
  
    <ol>{% if item.done %} 🟢
       {% else %}
        🔴
    {% endif %}
    
    
    {{ item.title }} 

    </ol>
    {% endfor %}
  </ul>
  -->  
  <table border="1">
    <thead>
        <tr>
            <th>Id</th>
            <th>Status</th>
            <th>Title</th>
        </tr>
    </thead>
    <tbody>
        {% for item in todo_list %}
        <tr>
            <td> <a href="{% url 'todo_list:detail' item.id %}">{{item.id}}</a></td>
            <td>
                {% if item.done %} 🟢 {% else %} 🔴 {% endif %}
            </td>
            <td>{{ item.title }}</td>
            <td>
                <a href="{% url 'todo_list:update' item.id %}">Edit</a>
            </td>
            <td>
                <a href="{% url 'todo_list:delete' item.id %}">Delete</a>
            </td>
            
        </tr>
        {% endfor %}
    </tbody>
</table>

todo_project/todo_list/templates/todo_list/index.html
{% extends 'todo_list/base.html' %} {% block body %}
<h3>ToDo Items List</h3>
{% include "todo_list/components/todo_items_list.html" %}

<h3>Categories List</h3>
{% include "todo_list/components/categories_list.html" %}
{% endblock body %}

todo_project/todo_list/templates/todo_list/todoitem_delete_form.html
{% extends 'todo_list/base.html' %} 

{% block title %} ToDo Form {% endblock %}




{% block body %}
<h3>Delete todo item:</h3>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

todo_project/todo_list/templates/todo_list/todoitem_detail.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDo #{{ object.pk }}
{% endblock %}

{% block body %}
  <h3>ToDo:</h3>
  <div>
    <div>Title: <strong>{{ object.title }}</strong></div>
    <div>Done: <strong>{{ object.done }}</strong></div>
    <div>Description: <strong>{{ object.description }}</strong></div>
  </div>
  <p></p>
{% endblock %}

todo_project/todo_list/templates/todo_list/todoitem_form.html
{% extends 'todo_list/base.html' %} 

{% block title %} ToDo Form {% endblock %}


{% block body %}
<h3>Create view todo form:</h3>
<form action="" method="post">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Send" />
</form>
{% endblock %}

todo_project/todo_list/templates/todo_list/todoitem_list.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDo List
{% endblock %}

{% block body %}
  <h3>ToDos:</h3>
  {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todo_project/todo_list/templates/todo_list/todoitem_update_form.html
{% extends 'todo_list/base.html' %} 

{% block title %} ToDo Form {% endblock %}


{% block body %}
<h3>Uptade todo item:</h3>
<form action="" method="post">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Update" />
</form>
{% endblock %}